---
- hosts: all
  tasks:
    - name: Update all Ubuntu packages
      apt:
        upgrade: "dist"
      when: ansible_distribution == 'Ubuntu'

    - name: Ensure postgres is installed and is latest
      apt:
        name: postgresql
        state: latest

    - name: Ensure postgres is running
      service:
        name: postgresql
        state: started

    - name: Install JDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Leiningen is installed and is latest
      apt:
        name: leiningen
        state: latest
